version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'pear2pear-db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      -  '27017-27019:27017-27019'